version: 0.2

phases:
  install:
    commands:
      - echo Installing Apache
      - sudo apt update
      - sudo apt install apache2 -y
      
  build:
    commands:
      - echo Moving to app directory
      - cd DAY-08/Sample-apache-app
      - ls

  post_build:
    commands:
      - echo Build completed
